eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka   


server:
  port: 8080

spring:  cloud:    gateway:      discovery:        locator:          enabled: true
          lower-case-service-id: true
                     application:    name: api-gateway
    
management:  endpoints:    web:      exposure:        include:        - "*"    
        
                