server:
  port: 6565
  
spring:
  application:
    name: secured-order-service
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root  
    password: srivatsan
    driver-class-name: com.mysql.cj.jdbc.Driver
  