server:
  port: 3030
  
spring:  application:    name: account-service
    

eureka:  client:    fetch-registry: true
    register-with-eureka: true
    service-url:      defaultZone: http://localhost:8761/eureka      