server:
  port: 3030
  
spring:
  application:
    name: account-service
  config:
    import: configserver:http://localhost:8888    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-peer2:8770/eureka           
