info:
  author: Srivatsan
  build:
    artificatId: '@project.artifact@'
    groupId: '@project.groupId@'
    version: '@project.version@'
  java:
      version:@java.version@
 

server:
  port: 3030
  
spring:
  application:
    name: account-service
  config:
    import: configserver:http://localhost:8888
  boot:
    admin:
      client:
        url: http://localhost:9494
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka           


management:  endpoints:    web:      exposure:        include:        - "*"
  endpoint:
    health:
      show-details: always
      
    shutdown:
      enabled: true  